export const UPDATE_CURRENT_VIDEO_ID = 'UPDATE_CURRENT_VIDEO_ID';
// export const UPDATE_VIDEO_DURATION = 'UPDATE_VIDEO_DURATION';
// export const UPDATE_ALL_COMMENT_COUNT = 'UPDATE_ALL_COMMENT_COUNT';
// export const UPDATE_FILTERED_ALL_COMMENT_COUNT = 'UPDATE_FILTERED_ALL_COMMENT_COUNT';
// export const UPDATE_COMMENT_ITEM = 'UPDATE_COMMENT_ITEM';
export const UPDATE_NEXT_PAGETOKEN = 'UPDATE_NEXT_PAGETOKEN';
export const UPDATE_SLIDEBAR_WIDTH_SIZE = 'UPDATE_SLIDEBAR_WIDTH_SIZE';
