export const UPDATE_FOO = 'UPDATE_FOO';
export const UPDATE_CURRENT_VIDEO_ID = 'UPDATE_CURRENT_VIDEO_ID';
export const UPDATE_VIDEO_DURATION = 'UPDATE_VIDEO_DURATION';
export const UPDATE_ALL_COMMENT_COUNT = 'UPDATE_ALL_COMMENT_COUNT';
export const UPDATE_FILTERED_ALL_COMMENT_COUNT = 'UPDATE_FILTERED_ALL_COMMENT_COUNT';
export const UPDATE_COMMENT_ITEM = 'UPDATE_COMMENT_ITEM';

export const UPDATE_NEXT_PAGETOKEN = 'UPDATE_NEXT_PAGETOKEN';
export const UPDATE_SLIDEBAR_WIDTH_SIZE = 'UPDATE_SLIDEBAR_WIDTH_SIZE';
// ALL COMMENTS REQUEST_STATUS
// VIDEO_DURATION REQUEST_STATUS

// nextPageToken_status -> ture -> false

// getSlideBarWidthSize
// changeSlideBarWitdh -> true/false

// SCURUBBER_DIV_STATUS = 'REMOVE_REQ' | REMOVED' | | 'ADD_REQ' |'ADDED'
// COMMENT_DIV_STATUS = 'REMOVED' | 'ADDED'
